on: push
jobs:
  build-containers:
    name:  Build container
    runs-on:  ubuntu-latest
    steps:
    - name: checkout code
      uses: action/checkout@v3
    - name: Login to doocker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_hub_username }}
        password: ${{ secrets.docker_hub_access_tocken }}